Updated `Django` to 4.2.21 to address `CVE-2025-32873`.
