Updated `Django` to 4.2.23 to further address `CVE-2025-48432`.
